#pragma config(Motor,  port2,           frontLefttMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           frontRightMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           backLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           backRightMotor, tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*  _______                     _    _       _ _                 
|* |__   __|                   | |  | |     (_|_)                 *\
|*    | | ___  __ _ _ __ ___   | |__| | __ _ _ _ _ __ ___   __ _  *|
|*    | |/ _ \/ _` | '_ ` _ \  |  __  |/ _` | | | '_ ` _ \ / _` | *|
|*    | |  __/ (_| | | | | | | | |  | | (_| | | | | | | | | (_| | *|
|*    |_|\___|\__,_|_| |_| |_| |_|  |_|\__,_| |_|_| |_| |_|\__,_| *|
|*                                         _/ |                   *|
|*                                        |__/                    *|
\*                                                                */



//*!! Controls with 4 Motors !!*/

task main()
{
  while(1 == 1)
  {
    //Right side of the robot is controlled by the right joystick, Y-axis
    motor[frontRightMotor] = vexRT[Ch2];
    motor[backRightMotor]  = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[frontLeftMotor] = vexRT[Ch3];
    motor[backLeftMotor]  = vexRT[Ch3];
  }
}
